"""Common message type constants for multi-terminal coordination."""

from __future__ import annotations

# Orchestrator -> PM
REQUEST_ARCHITECTURE = "REQUEST_ARCHITECTURE"
ARCHITECTURE_RESPONSE = "ARCHITECTURE_RESPONSE"

# Orchestrator -> Dev
REQUEST_IMPLEMENTATION = "REQUEST_IMPLEMENTATION"
IMPLEMENTATION_RESPONSE = "IMPLEMENTATION_RESPONSE"

# Orchestrator -> QA
REQUEST_QA_REVIEW = "REQUEST_QA_REVIEW"
QA_REVIEW_RESPONSE = "QA_REVIEW_RESPONSE"

# Orchestrator -> Security
REQUEST_SECURITY_REVIEW = "REQUEST_SECURITY_REVIEW"
SECURITY_REVIEW_RESPONSE = "SECURITY_REVIEW_RESPONSE"

# Utility commands
SHUTDOWN = "SHUTDOWN"
